<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sentinel.Analytics\Sentinel.Analytics.csproj" />
    <ProjectReference Include="..\Sentinel.Telemetry\Sentinel.Telemetry.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Sentinel.Tests" />
  </ItemGroup>
</Project>
