using System.Net;
using System.Text;
using System.Text.Json;
using Sentinel.Core.Privacy;

namespace Sentinel.Diagnostics.Reports;

/// <summary>Renders report documents. When the document is privacy-safe, every string passes through the redactor.</summary>
public static class ReportRenderer
{
    public static string Render(ReportDocument doc, ReportFormat format) => format switch
    {
        ReportFormat.Json => Json(doc),
        ReportFormat.Csv => Csv(doc),
        _ => Html(doc),
    };

    private static string R(ReportDocument d, string? s) => s is null ? "" : d.PrivacySafe ? Redactor.Redact(s) : s;

    public static string Html(ReportDocument d)
    {
        var sb = new StringBuilder();
        string E(string? s) => WebUtility.HtmlEncode(R(d, s));
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">");
        sb.Append("<title>").Append(E(d.Title)).Append("</title><style>");
        sb.Append("""
            :root{--bg:#f7f7f8;--card:#fff;--text:#1b1b1f;--muted:#5f6068;--line:#e3e3e8;--accent:#2563eb}
            @media (prefers-color-scheme:dark){:root{--bg:#141417;--card:#1d1d21;--text:#ececf1;--muted:#9a9aa5;--line:#2c2c33;--accent:#7aa2ff}}
            *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.55 "Segoe UI Variable Text","Segoe UI",system-ui,sans-serif}
            main{max-width:980px;margin:0 auto;padding:40px 20px 80px}header{margin-bottom:28px}
            h1{font-size:28px;font-weight:600;margin:0 0 6px}h2{font-size:18px;font-weight:600;margin:0 0 12px}h3{font-size:14px;margin:18px 0 8px;color:var(--muted);font-weight:600;text-transform:uppercase;letter-spacing:.04em}
            .meta{color:var(--muted);font-size:13px}section{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:20px 22px;margin:16px 0}
            dl{display:grid;grid-template-columns:minmax(160px,34%) 1fr;gap:6px 16px;margin:0}dt{color:var(--muted)}dd{margin:0;word-break:break-word}
            .wrap{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);vertical-align:top}
            th{color:var(--muted);font-weight:600}p{margin:0 0 10px}.badge{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:1px 10px;font-size:12px;color:var(--muted)}
            """);
        sb.Append("</style></head><body><main><header><h1>").Append(E(d.Title)).Append("</h1><div class=\"meta\">Generated by Sentinel on ")
            .Append(E(d.Generated.ToString("f", System.Globalization.CultureInfo.CurrentCulture))).Append(" · ")
            .Append(d.PrivacySafe ? "<span class=\"badge\">Privacy-safe: personal identifiers removed</span>" : "<span class=\"badge\">Contains identifiers</span>")
            .Append("</div></header>");
        foreach (var s in d.Sections)
        {
            sb.Append("<section><h2>").Append(E(s.Heading)).Append("</h2>");
            foreach (var p in s.Paragraphs) sb.Append("<p>").Append(E(p)).Append("</p>");
            if (s.Facts.Count > 0)
            {
                sb.Append("<dl>");
                foreach (var (l, v) in s.Facts) sb.Append("<dt>").Append(E(l)).Append("</dt><dd>").Append(E(v)).Append("</dd>");
                sb.Append("</dl>");
            }
            foreach (var t in s.Tables)
            {
                sb.Append("<h3>").Append(E(t.Title)).Append("</h3><div class=\"wrap\"><table><thead><tr>");
                foreach (var c in t.Columns) sb.Append("<th>").Append(E(c)).Append("</th>");
                sb.Append("</tr></thead><tbody>");
                foreach (var row in t.Rows)
                {
                    sb.Append("<tr>");
                    foreach (var cell in row) sb.Append("<td>").Append(E(cell)).Append("</td>");
                    sb.Append("</tr>");
                }
                sb.Append("</tbody></table></div>");
            }
            sb.Append("</section>");
        }
        sb.Append("<p class=\"meta\">Sentinel is read-only: it observed this PC and changed nothing. This report was created locally and has not been uploaded anywhere.</p>");
        sb.Append("</main></body></html>");
        return sb.ToString();
    }

    public static string Json(ReportDocument d)
    {
        var obj = new
        {
            title = R(d, d.Title),
            kind = d.Kind.ToString(),
            generated = d.Generated,
            privacySafe = d.PrivacySafe,
            sections = d.Sections.Select(s => new
            {
                heading = R(d, s.Heading),
                paragraphs = s.Paragraphs.Select(p => R(d, p)),
                facts = s.Facts.Select(f => new { label = R(d, f.Label), value = R(d, f.Value) }),
                tables = s.Tables.Select(t => new
                {
                    title = R(d, t.Title),
                    columns = t.Columns,
                    rows = t.Rows.Select(r => r.Select(c => R(d, c))),
                }),
            }),
        };
        return JsonSerializer.Serialize(obj, new JsonSerializerOptions { WriteIndented = true });
    }

    /// <summary>One CSV containing every table, prefixed with section and table names.</summary>
    public static string Csv(ReportDocument d)
    {
        var sb = new StringBuilder();
        foreach (var s in d.Sections)
        {
            foreach (var (l, v) in s.Facts) Line(sb, [s.Heading, "Fact", l, v], d);
            foreach (var t in s.Tables)
            {
                Line(sb, [s.Heading, t.Title, .. t.Columns], d);
                foreach (var row in t.Rows) Line(sb, [s.Heading, t.Title, .. row], d);
            }
        }
        return sb.ToString();
    }

    private static void Line(StringBuilder sb, IEnumerable<string> cells, ReportDocument d)
    {
        sb.AppendLine(string.Join(",", cells.Select(c =>
        {
            var v = R(d, c);
            // Neutralise spreadsheet formula injection from untrusted values.
            if (v.Length > 0 && v[0] is '=' or '+' or '-' or '@') v = "'" + v;
            return "\"" + v.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";
        })));
    }
}
